export const APP_NAME = 'SurajAI';
export const API_VERSION = 'v1';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;
